source 'https://github.com/CocoaPods/Specs.git'

target 'RCRestTableView' do
  pod "RCRestTableView", :path => "../"

  target "Tests" do
    inherit! :search_paths
    pod 'Specta', '~> 0.5'
	pod 'Expecta'
  end
end