source 'https://github.com/CocoaPods/Specs.git'

target :RCRestTableView, :exclusive => true do
  pod "RCRestTableView", :path => "../"
end

target :Tests, :exclusive => true do
	pod "RCRestTableView", :path => "../"
	pod 'Specta', '~> 0.5'
	pod 'Expecta'
end